global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        # - alertmanager:9093

rule_files: # - rules.yml"

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: [ "localhost:9090" ]

- job_name: 'postgres'
  static_configs:
  - targets: [ 'postgres-exporter:9187' ]

- job_name: 'app-a'
  scrape_interval: 5s

  static_configs:
  - targets: [ 'app-a:8000' ]

- job_name: 'app-b'
  scrape_interval: 5s
  static_configs:
  - targets: [ 'app-b:8000' ]

- job_name: 'app-c'
  scrape_interval: 5s
  static_configs:
  - targets: [ 'app-c:8000' ]
